### ISSUE TITLE
add `key`, `cert` in agentOptions method in lib/request.js

### ISSUE THREAD

**Issue by fas3r** [jkyberneees/fast-proxy#1]
Hello, 

would it be possible to add `key` and `cert` in the method [agentOptions](https://github.com/jkyberneees/fast-proxy/blob/d3f009e98b29e2f59c1bee538afb89496c973227/lib/request.js#L132) please ? 

The use case is if the backend use TLS auth.

Thanks

**Comment by jkyberneees** [comment]
Hi @fas3r, totally valid issue. I will update and release ASAP. 
Thanks.

**Comment by jkyberneees** [comment]
Hi @fas3r, from v1.2.0, you can now pass down all supported Agent configurations via the `opts` param.

Thanks for reporting.
